# Override file for local development
# This file automatically extends docker-compose.yml

services:
  api-dev:
    environment:
      # Override with your local settings
      DEBUG: "api:*"
      LOG_LEVEL: debug
    volumes:
      # Additional volume mounts for development
      - ./logs:/app/logs
    # Uncomment to enable debugging
    # ports:
    #   - "9229:9229"
    # command: ["npm", "run", "dev:debug"]

  mongodb:
    ports:
      # Expose MongoDB port for local database tools
      - "27017:27017"
    # volumes:
      # Optional: Add custom MongoDB configuration
      # - ./mongo.conf:/etc/mongod.conf.orig

  # Uncomment to add a database admin interface
  # mongo-express:
  #   image: mongo-express
  #   container_name: city-price-planner-admin
  #   restart: unless-stopped
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: admin
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: password123
  #     ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - city-price-planner-network
